DROP DATABASE IF EXISTS engine_db;
CREATE DATABASE engine_db;
USE engine_db;

DROP TABLE IF EXISTS department;

CREATE TABLE department (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL);